// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// serverInitDualAveragingCpp
List serverInitDualAveragingCpp(List config);
RcppExport SEXP _FederatedLearning_serverInitDualAveragingCpp(SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(serverInitDualAveragingCpp(config));
    return rcpp_result_gen;
END_RCPP
}
// clientUpdateDualAveragingCpp
List clientUpdateDualAveragingCpp(List& clientData, List& serverBroadcast, List& config);
RcppExport SEXP _FederatedLearning_clientUpdateDualAveragingCpp(SEXP clientDataSEXP, SEXP serverBroadcastSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type clientData(clientDataSEXP);
    Rcpp::traits::input_parameter< List& >::type serverBroadcast(serverBroadcastSEXP);
    Rcpp::traits::input_parameter< List& >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(clientUpdateDualAveragingCpp(clientData, serverBroadcast, config));
    return rcpp_result_gen;
END_RCPP
}
// serverRoundDualAveragingCpp
List serverRoundDualAveragingCpp(List& serverState, List& clientReports, List& config);
RcppExport SEXP _FederatedLearning_serverRoundDualAveragingCpp(SEXP serverStateSEXP, SEXP clientReportsSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type serverState(serverStateSEXP);
    Rcpp::traits::input_parameter< List& >::type clientReports(clientReportsSEXP);
    Rcpp::traits::input_parameter< List& >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(serverRoundDualAveragingCpp(serverState, clientReports, config));
    return rcpp_result_gen;
END_RCPP
}
// cyclopsGradientObjectiveCpp
double cyclopsGradientObjectiveCpp(const Eigen::Map<Eigen::SparseMatrix<double> >& x, const Eigen::VectorXd& beta, const Eigen::VectorXd& y);
RcppExport SEXP _FederatedLearning_cyclopsGradientObjectiveCpp(SEXP xSEXP, SEXP betaSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double> >& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(cyclopsGradientObjectiveCpp(x, beta, y));
    return rcpp_result_gen;
END_RCPP
}
// logisticGradientCpp
Eigen::VectorXd logisticGradientCpp(const Eigen::Map<Eigen::SparseMatrix<double> >& x, const Eigen::VectorXd& beta, const Eigen::VectorXd& y, double eps);
RcppExport SEXP _FederatedLearning_logisticGradientCpp(SEXP xSEXP, SEXP betaSEXP, SEXP ySEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double> >& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(logisticGradientCpp(x, beta, y, eps));
    return rcpp_result_gen;
END_RCPP
}
// logisticGradientHessianDiagCpp
List logisticGradientHessianDiagCpp(const Eigen::Map<Eigen::SparseMatrix<double> >& x, const Eigen::VectorXd& beta, const Eigen::VectorXd& y, double eps);
RcppExport SEXP _FederatedLearning_logisticGradientHessianDiagCpp(SEXP xSEXP, SEXP betaSEXP, SEXP ySEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double> >& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(logisticGradientHessianDiagCpp(x, beta, y, eps));
    return rcpp_result_gen;
END_RCPP
}
// logisticHessianDiagCpp
Eigen::VectorXd logisticHessianDiagCpp(const Eigen::Map<Eigen::SparseMatrix<double> >& x, const Eigen::VectorXd& beta, double eps);
RcppExport SEXP _FederatedLearning_logisticHessianDiagCpp(SEXP xSEXP, SEXP betaSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double> >& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(logisticHessianDiagCpp(x, beta, eps));
    return rcpp_result_gen;
END_RCPP
}
// logisticHessianCpp
Eigen::MatrixXd logisticHessianCpp(const Eigen::Map<Eigen::SparseMatrix<double> >& x, const Eigen::VectorXd& beta, double eps);
RcppExport SEXP _FederatedLearning_logisticHessianCpp(SEXP xSEXP, SEXP betaSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double> >& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(logisticHessianCpp(x, beta, eps));
    return rcpp_result_gen;
END_RCPP
}
// logisticGradientHessianCpp
List logisticGradientHessianCpp(const Eigen::Map<Eigen::SparseMatrix<double> >& x, const Eigen::VectorXd& beta, const Eigen::VectorXd& y, double eps);
RcppExport SEXP _FederatedLearning_logisticGradientHessianCpp(SEXP xSEXP, SEXP betaSEXP, SEXP ySEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double> >& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(logisticGradientHessianCpp(x, beta, y, eps));
    return rcpp_result_gen;
END_RCPP
}
// quadraticLassoCdCpp
Eigen::VectorXd quadraticLassoCdCpp(const Eigen::VectorXd& aTilde, const Eigen::MatrixXd& bMatrix, const Eigen::VectorXd& betaInit, double lambda, int maxIter, double tol, Rcpp::Nullable<Rcpp::LogicalVector> penalizeNullable);
RcppExport SEXP _FederatedLearning_quadraticLassoCdCpp(SEXP aTildeSEXP, SEXP bMatrixSEXP, SEXP betaInitSEXP, SEXP lambdaSEXP, SEXP maxIterSEXP, SEXP tolSEXP, SEXP penalizeNullableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type aTilde(aTildeSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type bMatrix(bMatrixSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type betaInit(betaInitSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type maxIter(maxIterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::LogicalVector> >::type penalizeNullable(penalizeNullableSEXP);
    rcpp_result_gen = Rcpp::wrap(quadraticLassoCdCpp(aTilde, bMatrix, betaInit, lambda, maxIter, tol, penalizeNullable));
    return rcpp_result_gen;
END_RCPP
}
// adapFullSurrogateFitCpp
List adapFullSurrogateFitCpp(const Eigen::Map<Eigen::SparseMatrix<double> >& x, const Eigen::VectorXd& y, const Eigen::VectorXd& betaStart, const Eigen::VectorXd& betaBar, const Eigen::VectorXd& globalGrad, const Eigen::MatrixXd& globalHess, const Eigen::VectorXd& gradBar, const Eigen::MatrixXd& hBar, double lambda, int maxOuter, int maxInner, double tol, double eps);
RcppExport SEXP _FederatedLearning_adapFullSurrogateFitCpp(SEXP xSEXP, SEXP ySEXP, SEXP betaStartSEXP, SEXP betaBarSEXP, SEXP globalGradSEXP, SEXP globalHessSEXP, SEXP gradBarSEXP, SEXP hBarSEXP, SEXP lambdaSEXP, SEXP maxOuterSEXP, SEXP maxInnerSEXP, SEXP tolSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double> >& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type betaStart(betaStartSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type betaBar(betaBarSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type globalGrad(globalGradSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type globalHess(globalHessSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type gradBar(gradBarSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type hBar(hBarSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type maxOuter(maxOuterSEXP);
    Rcpp::traits::input_parameter< int >::type maxInner(maxInnerSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(adapFullSurrogateFitCpp(x, y, betaStart, betaBar, globalGrad, globalHess, gradBar, hBar, lambda, maxOuter, maxInner, tol, eps));
    return rcpp_result_gen;
END_RCPP
}
// adapFirstSurrogateFitCpp
List adapFirstSurrogateFitCpp(const Eigen::Map<Eigen::SparseMatrix<double> >& x, const Eigen::VectorXd& y, const Eigen::VectorXd& betaStart, const Eigen::VectorXd& betaBar, const Eigen::VectorXd& globalGrad, const Eigen::VectorXd& gradBar, double lambda, int maxOuter, int maxInner, double tol, double eps);
RcppExport SEXP _FederatedLearning_adapFirstSurrogateFitCpp(SEXP xSEXP, SEXP ySEXP, SEXP betaStartSEXP, SEXP betaBarSEXP, SEXP globalGradSEXP, SEXP gradBarSEXP, SEXP lambdaSEXP, SEXP maxOuterSEXP, SEXP maxInnerSEXP, SEXP tolSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double> >& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type betaStart(betaStartSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type betaBar(betaBarSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type globalGrad(globalGradSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type gradBar(gradBarSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type maxOuter(maxOuterSEXP);
    Rcpp::traits::input_parameter< int >::type maxInner(maxInnerSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(adapFirstSurrogateFitCpp(x, y, betaStart, betaBar, globalGrad, gradBar, lambda, maxOuter, maxInner, tol, eps));
    return rcpp_result_gen;
END_RCPP
}
// adapDiagSurrogateFitCpp
List adapDiagSurrogateFitCpp(const Eigen::Map<Eigen::SparseMatrix<double> >& x, const Eigen::VectorXd& y, const Eigen::VectorXd& betaStart, const Eigen::VectorXd& betaBar, const Eigen::VectorXd& globalGrad, const Eigen::VectorXd& globalHessDiag, const Eigen::VectorXd& gradBar, const Eigen::VectorXd& hBarDiag, double lambda, int maxOuter, int maxInner, double tol, double eps);
RcppExport SEXP _FederatedLearning_adapDiagSurrogateFitCpp(SEXP xSEXP, SEXP ySEXP, SEXP betaStartSEXP, SEXP betaBarSEXP, SEXP globalGradSEXP, SEXP globalHessDiagSEXP, SEXP gradBarSEXP, SEXP hBarDiagSEXP, SEXP lambdaSEXP, SEXP maxOuterSEXP, SEXP maxInnerSEXP, SEXP tolSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double> >& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type betaStart(betaStartSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type betaBar(betaBarSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type globalGrad(globalGradSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type globalHessDiag(globalHessDiagSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type gradBar(gradBarSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type hBarDiag(hBarDiagSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type maxOuter(maxOuterSEXP);
    Rcpp::traits::input_parameter< int >::type maxInner(maxInnerSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(adapDiagSurrogateFitCpp(x, y, betaStart, betaBar, globalGrad, globalHessDiag, gradBar, hBarDiag, lambda, maxOuter, maxInner, tol, eps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FederatedLearning_serverInitDualAveragingCpp", (DL_FUNC) &_FederatedLearning_serverInitDualAveragingCpp, 1},
    {"_FederatedLearning_clientUpdateDualAveragingCpp", (DL_FUNC) &_FederatedLearning_clientUpdateDualAveragingCpp, 3},
    {"_FederatedLearning_serverRoundDualAveragingCpp", (DL_FUNC) &_FederatedLearning_serverRoundDualAveragingCpp, 3},
    {"_FederatedLearning_cyclopsGradientObjectiveCpp", (DL_FUNC) &_FederatedLearning_cyclopsGradientObjectiveCpp, 3},
    {"_FederatedLearning_logisticGradientCpp", (DL_FUNC) &_FederatedLearning_logisticGradientCpp, 4},
    {"_FederatedLearning_logisticGradientHessianDiagCpp", (DL_FUNC) &_FederatedLearning_logisticGradientHessianDiagCpp, 4},
    {"_FederatedLearning_logisticHessianDiagCpp", (DL_FUNC) &_FederatedLearning_logisticHessianDiagCpp, 3},
    {"_FederatedLearning_logisticHessianCpp", (DL_FUNC) &_FederatedLearning_logisticHessianCpp, 3},
    {"_FederatedLearning_logisticGradientHessianCpp", (DL_FUNC) &_FederatedLearning_logisticGradientHessianCpp, 4},
    {"_FederatedLearning_quadraticLassoCdCpp", (DL_FUNC) &_FederatedLearning_quadraticLassoCdCpp, 7},
    {"_FederatedLearning_adapFullSurrogateFitCpp", (DL_FUNC) &_FederatedLearning_adapFullSurrogateFitCpp, 13},
    {"_FederatedLearning_adapFirstSurrogateFitCpp", (DL_FUNC) &_FederatedLearning_adapFirstSurrogateFitCpp, 11},
    {"_FederatedLearning_adapDiagSurrogateFitCpp", (DL_FUNC) &_FederatedLearning_adapDiagSurrogateFitCpp, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_FederatedLearning(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
