# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
serverInitDualAveragingCpp <- function(config) {
    .Call(`_FederatedLearning_serverInitDualAveragingCpp`, config)
}

#' @export
clientUpdateDualAveragingCpp <- function(clientData, serverBroadcast, config) {
    .Call(`_FederatedLearning_clientUpdateDualAveragingCpp`, clientData, serverBroadcast, config)
}

#' @export
serverRoundDualAveragingCpp <- function(serverState, clientReports, config) {
    .Call(`_FederatedLearning_serverRoundDualAveragingCpp`, serverState, clientReports, config)
}

cyclopsGradientObjectiveCpp <- function(x, beta, y) {
    .Call(`_FederatedLearning_cyclopsGradientObjectiveCpp`, x, beta, y)
}

logisticGradientCpp <- function(x, beta, y, eps = 1e-8) {
    .Call(`_FederatedLearning_logisticGradientCpp`, x, beta, y, eps)
}

logisticGradientHessianDiagCpp <- function(x, beta, y, eps = 1e-8) {
    .Call(`_FederatedLearning_logisticGradientHessianDiagCpp`, x, beta, y, eps)
}

logisticHessianDiagCpp <- function(x, beta, eps = 1e-8) {
    .Call(`_FederatedLearning_logisticHessianDiagCpp`, x, beta, eps)
}

logisticHessianCpp <- function(x, beta, eps = 1e-8) {
    .Call(`_FederatedLearning_logisticHessianCpp`, x, beta, eps)
}

logisticGradientHessianCpp <- function(x, beta, y, eps = 1e-8) {
    .Call(`_FederatedLearning_logisticGradientHessianCpp`, x, beta, y, eps)
}

