# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Initialize the C++ dual-averaging server state
#' @param config algorithm configuration list
#' @return server state list
#' @export
serverInitDualAveragingCpp <- function(config) {
    .Call(`_FederatedLearning_serverInitDualAveragingCpp`, config)
}

#' Run a C++ dual-averaging client update
#' @param clientData local client data list
#' @param serverBroadcast server state broadcast to the client
#' @param config algorithm configuration list
#' @return client update report
#' @export
clientUpdateDualAveragingCpp <- function(clientData, serverBroadcast, config) {
    .Call(`_FederatedLearning_clientUpdateDualAveragingCpp`, clientData, serverBroadcast, config)
}

#' Run a C++ dual-averaging server round
#' @param serverState current server state
#' @param clientReports list of client update reports
#' @param config algorithm configuration list
#' @return list with updated server state and report
#' @export
serverRoundDualAveragingCpp <- function(serverState, clientReports, config) {
    .Call(`_FederatedLearning_serverRoundDualAveragingCpp`, serverState, clientReports, config)
}
